version: '3.9'

services:
  skyble-website:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: skyble-website
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_BASE_PATH=
    # Add healthcheck for production reliability
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
    # Reduce container privileges for security
    security_opt:
      - no-new-privileges:true 